version: '3.3'

services:
  hoouse:
    build: ./
    command: ./house
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "house"
      POSTGRES_PASSWORD: 123
    ports:
      - "5436:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql